jobs:
  test:
    name: Linux Flutter Unit Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 12.x
    - continue-on-error: true
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 2.0.4
    - continue-on-error: true
      run: flutter doctor
    - continue-on-error: true
      run: flutter pub get
    - continue-on-error: true
      run: flutter test
name: Flutter Unit Tests
on:
  repository_dispatch:
    types: trigger-ga___flutter_ut.yml
